### ISSUE TITLE
Question: why does `&nbsp;` convert to `\n`

### ISSUE THREAD

**Issue by simonratner** [Favna/unescape-es6#12]
Seems like `<space>` would be a more appropriate conversion.

**Comment by Favna** [comment]
Wew I didn't see this nor the other issue notify me. That's odd. 

Anyway, normally `&nbsp;` would mean the user wants a breaking line space I think? I actually can't find any documentation on `<space>`. In fact, [this article](https://www.lifewire.com/html-space-tag-3466504) says it doesn't even exist.

Can you provide a source for `<space>`?

**Comment by simonratner** [comment]
By `<space>` I meant a single space character, ascii 32 -- apologies for my confusing notation. The `&nbsp;` entity represents a "non-breaking space", it never renders as a line break and is in fact the opposite of a line break 😁. 

I think the closest ascii translation is a simple space.

**Comment by Favna** [comment]
Released in [version 2.0.5](https://www.npmjs.com/package/unescape-es6/v/2.0.5
